image: node:16.8.0

stages:
    - lint
    - lint-production
    - build

before_script:
    - npm install

lint:
    stage: lint
    script:
        - npm run lint
    rules:
        - if: $CI_COMMIT_BRANCH == "main"
          when: never
        - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
          when: never

lint-production:
    stage: lint-production
    script:
        - npm run lint:prodution
    rules:
        - if: $CI_COMMIT_BRANCH == "main"
        - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"

build:
    stage: build
    script:
        - npm run build:next
    rules:
        - if: $CI_COMMIT_BRANCH == "main"
        - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
