image: node:latest

stages:
  - lint
  - build

before_script:
  - npm install

# Lint source code with es lint
eslint:
  stage: lint
  script:
    - echo "ESLint Frontend"
    - cd src && npm run lint
    - cd ..
    - echo "ESLint Backend"
    - echo "TODO implement" # TODO: configure

# Test the App by building it
nextBuild:
  stage: build
  script:
    - echo "Test if the Frontend builds successfully"
    - cd src && npm run build
    - cd ..
    - echo "Test if the Backend builds successfully"
    - echo "TODO implement" # TODO: configure

