# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '30 22 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue is set to stale because no activity occured within 90 days. It will be closed within the next year.'
        close-issue-message: 'This issue was finally closed due to long inactivity.'
        stale-issue-label: 'status: frozen'
        stale-pr-message: 'This PR is set to stale because no activity occured within 90 days. It will be closed within the next year.'
        close-pr-message: 'This PR was finally closed due to long inactivity.'
        stale-pr-label: 'status: frozen'
        days-before-stale: 90
        days-before-close: 365
